
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author i
 */
public class photo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form photo
     */
    public photo() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //demo3.count++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\oop_assignments\\project\\iconphoto.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(778, 436, 234, 258);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(834, 770, 105, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\i\\Downloads\\forever.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 90, 242, 208);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("High Tower Text", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Upload Photo");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(950, 210, 274, 80);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Skip>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(834, 855, 109, 37);

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\oop_assignments\\project\\backicn.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 100, 70, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\oop_assignments\\project\\freestocks-org-82348-unsplash.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(5, 6, 2360, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String password = this.password.getText();
        
        Connection con;
        Statement st = null;
        Statement str = null;

        ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projectx", "root", "");

            //"INSERT INTO `customer_details`() VALUES ('"+ persnl_detail.first +"','"+ persnl_detail.last +"',"+ persnl_detail.fmember +",'"+ persnl_detail.num +"',"+ persnl_detail.heig +","+ persnl_detail.weig +",'"+ education.educ +"','"+ education.uni +"','"+ education.yea +"',"+ education.ag +",'"+ education.jo +"','"+ education.salar +"','"+ religious.cas +"','"+ religious.subcas +"','"+ religious.mtongu +"','"+ religious.lifestyl +"','"+ religious.bgrou +"','"+ religious.explai +"','"+ religious.habit +"','"+ religious.marita +"',"+ demo3.count+")";
            int i = 0;
//              int i = str.executeUpdate(sti);
//            if (i == 1) {
//                System.out.println("updated successfully");
//            } else {
//                System.out.println("not upadted");
//            }
String str1="insert into customer_details(first_name, last_name, f_members, hobbies, height, weight, education, university, year_passed, age, job, salary, cast, sub_cast, m_tongue, lifestyle, b_group, explain_me, habits, martial_state,image, CustomerID) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(str1);
                           
            
            //JFrame f = new JFrame();
            //rs = st.executeQuery("SELECT * FROM `customer` WHERE 1");
            JFileChooser fc = new JFileChooser();
            int rv = fc.showOpenDialog(this);
            if (rv == JFileChooser.APPROVE_OPTION) {
                File sf = fc.getSelectedFile();
                String x = fc.getName(sf);
                System.out.println(x);
                FileInputStream fim = new FileInputStream(sf);
                pst.setString(1, persnl_detail.first);
                pst.setString(2, persnl_detail.last);
                pst.setInt(3, persnl_detail.fmember);
                pst.setString(4, persnl_detail.num);
              //  pst.setString(5,persnl_detail.b);
                pst.setFloat(5, persnl_detail.heig);
                pst.setFloat(6, persnl_detail.weig);
                pst.setString(7, education.educ);
                pst.setString(8, education.uni);
                pst.setString(9, education.yea);
                pst.setInt(10, education.ag);
                pst.setString(11, education.jo);
                pst.setString(12, education.salar);
                pst.setString(13, religious.cas);
                pst.setString(14, religious.subcas);
                pst.setString(15, religious.mtongu);
                pst.setString(16, religious.lifestyl);
                pst.setString(17, religious.bgrou);
                pst.setString(18 ,religious.explai);
                pst.setString(19 ,religious.habit);
                pst.setString(20, religious.marita);

                pst.setBinaryStream(21, fim, fim.available());
                pst.setInt(22, question1.registerid);

                i = pst.executeUpdate();
                                 System.out.println("query"+str1);

                if (i == 1) {
                    System.out.println("successfully updated");
                } else {
                    System.out.println("error");
                }
            }

////            try {
////                f1.createNewFile();
////            } catch (IOException ex) {
////                Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
////            }
////

// File file = new File("D:\\oop_assignments\\project\\image\\user"+question1.registerid+".jpeg");
//           boolean fvar = file.createNewFile();
//            if (fvar) {
//                System.out.println("created successfully");
//            }
//          else{
//              System.out.println("not created ");
//          }
//////            System.out.println("file "+sf.getName());
//FileOutputStream fout = new FileOutputStream("D:\\oop_assignments\\project\\image\\user"+question1.registerid+".jpeg");
//            byte b[];
//            Blob blob;
//            
//            //JFrame f = new JFrame();
//            rs = st.executeQuery("SELECT * FROM `customer_details`,`customer` WHERE customer.CustomerID=23 && customer_details.CustomerID=23");
//            //int flag = 0, i = 0
//
//            while (rs.next()) {
//                blob = rs.getBlob("image");
//                b = blob.getBytes(1, (int) blob.length());
//                fout.write(b);
//                System.out.println("abcd");
//            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
        }
          this.setVisible(false);
      Homepage bq=new Homepage();
        bq.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed
//
//        } catch (ClassNotFoundException ex) {
//            //   Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(ex);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(ex);
//        } catch (IOException ex) {
//            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(ex);
//        }

        

 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
      Homepage bq=new Homepage();
        bq.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 this.setVisible(false);
      religious bq=new religious();
        bq.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(photo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(photo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(photo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(photo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new photo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
